# Generated by Django 6.0.1 on 2026-04-05 09:00

import appointment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=appointment.models.get_default_expiration),
        ),
    ]
